<?php

/**
 * Model_Base_Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $generationdate
 * @property float $amount
 * @property timestamp $duedate
 * @property timestamp $paymentdate
 * @property Model_Session $Session
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Invoice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('invoice');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('generationdate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('duedate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('paymentdate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Session as Session', array(
             'local' => 'id',
             'foreign' => 'invoiceid'));
    }
}