<?php

/**
 * Model_Base_Session
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $sessiontype
 * @property string $description
 * @property string $location
 * @property timestamp $datetime
 * @property string $length
 * @property integer $userid
 * @property integer $groupid
 * @property integer $invoiceid
 * @property Model_User $User
 * @property Model_Usergroup $Usergroup
 * @property Model_Invoice $Invoice
 * @property Doctrine_Collection $Results
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Session extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sessiontype', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('location', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('datetime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('length', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('userid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('groupid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('invoiceid', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as User', array(
             'local' => 'userid',
             'foreign' => 'id'));

        $this->hasOne('Model_Usergroup as Usergroup', array(
             'local' => 'groupid',
             'foreign' => 'id'));

        $this->hasOne('Model_Invoice as Invoice', array(
             'local' => 'invoiceid',
             'foreign' => 'id'));

        $this->hasMany('Model_Result as Results', array(
             'local' => 'id',
             'foreign' => 'sessionid'));
    }
}