<?php $this->headLink()->appendStylesheet('/css/calendar.css'); ?>
<?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'); ?>
<?php $this->headScript()->appendFile('/scripts/jquery.jcarousel.min.js'); ?>
<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
    $("ul#monthCarousel").jcarousel({
        scroll: 3,
        visible: 3,
        start: Math.min($('li#selected-month').index(),$('ul#monthCarousel > li').length - 1),
        animation: 800
    });
});
<?php $this->headScript()->captureEnd(); ?>
<div id="calendarWrapper">
    <div id="calendarHeader">
        <div id="scrollableWrapper">
            <ul id="monthCarousel" class="jcarousel-skin-custom">
            <?php
            $calHeader = $this->calendar->getCalendarHeaderDataArray(
                        'user', //controller
                        'index' //action
                );
            foreach ($calHeader as $arr) : ?>
                <li id="<?php echo $arr['id']; ?>">
                    <a href="<?php echo $this->url($arr['url']); ?>"><?php echo $arr['text']; ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div id="calendarBody">
        <table id="calendarTable" border="0" cellpadding="0" cellspacing="0">
            <tr class="weekdays">
                <?php foreach($this->calendar->getDayNames() as $dayName) : ?>
                <td class="<?php echo $dayName['class']; ?>"><?=$dayName['name'];?></td>
                <?php endforeach;?>
            </tr>
            <?php foreach ($this->calendar->weekList as $weekNum => $weekArr) : ?>
            <tr class="days">
            <?php foreach ($weekArr as $dayArr) : ?>
                <?php $class = ""; ?>
                <?php if ($dayArr['day']->isToday()) $class .= "today"; ?>
                <?php if ($dayArr['day']->get(Zend_Date::WEEKDAY_DIGIT) == 6) $class .= " last"; ?>
                <?php if ($dayArr['day']->get(Zend_Date::MONTH) != $this->calendar->get(Zend_Date::MONTH)) {
                          $class .= ' nonmonth';
                      }
                ?>
                <td <?php if ($class != "") echo "class=\"$class\""; ?>>
                <?php if (isset($dayArr['day'])) : ?>
                    <span class="dayNum"><?php echo $dayArr['day']; ?></span>
                <?php endif; ?>
                <?php
                    $maxEvents = 4;
                    // Grab info for day

                    $events = null;
                    if (!empty($dayArr['events'])) {
                        foreach($dayArr['events'] as $dayEvent){
                            $events[] = $this->calendar->getEvent($dayEvent['id']);
                        }
                        
                        #unset($dayArr['events'][key($dayArr['events'])]);
                    }

                    #if (empty($dayInfo['events'])) unset($dayArr);
                ?>
                <?php if ($events) : ?>
                    <?php foreach($events as $event): ?>
                    <span class="event">
                        <?php if ($event->title == 'PT Session'): ?>
                        <a href="/user/session/id/<?=$event->id;?>">
                        <?php else: ?>
                        <a href="/user/diary/id/<?=$event->id;?>">
                        <?php endif; ?>
                            <?=$event->title;?>
                        </a>
                    </span>
                    <?php endforeach; ?>
                <?php endif;?>
                </td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>