<?php $this->headLink()->appendStylesheet('/css/calendar.css'); ?>
<?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'); ?>
<?php $this->headScript()->appendFile('/scripts/jquery.jcarousel.min.js'); ?>
<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
    $("ul#monthCarousel").jcarousel({
        scroll: 3,
        visible: 3,
        start: Math.min($('li#selected-month').index(),$('ul#monthCarousel > li').length - 1),
        animation: 800
    });
});
<?php $this->headScript()->captureEnd(); ?>
<div id="calendarWrapper">
    <div id="calendarHeader">
        <div id="scrollableWrapper">
            <ul id="monthCarousel" class="jcarousel-skin-custom">
            <?php
            $calHeader = $this->calendar->calHeader;
            foreach ($calHeader as $arr) : ?>
                <li id="<?php echo $arr['id']; ?>">
                    <a href="<?php echo $this->url($arr['url']); ?>"><?php echo $arr['text']; ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div id="calendarBody">
        <table id="calendarTable" border="0" cellpadding="0" cellspacing="0">
            <tr class="weekdays">
                <?php foreach($this->calendar->getDayNames() as $dayName) : ?>
                <td class="<?php echo $dayName['class']; ?>"><?=$dayName['name'];?></td>
                <?php endforeach;?>
            </tr>
            <?php foreach ($this->calendar->weekList as $weekNum => $weekArr) : ?>
            <tr class="days">
            <?php foreach ($weekArr as $dayArr) : ?>
                <?php $class = $dayArr['day']->getClass(); ?>
                <td <?php if ($class != "") echo "class=\"$class\""; ?>>
                <?php if (isset($dayArr['day'])) : ?>
                    <span class="dayNum"><?php echo $dayArr['day']; ?></span>
                <?php endif; ?>
                <?php
                    $maxEvents = 4;

                    // Grab info for day
                    $events = null;
                    if (!empty($dayArr['events'])) {
                        for ($i = 0; $i < $maxEvents; $i++){
                            if (isset($dayArr['events'][$i])){
                                $dayEvent = $dayArr['events'][$i];
                                $events[] = $this->calendar->getEvent($dayEvent['id']);
                            }
                        }
                    }
                ?>
                <?php if ($events) : ?>
                    <span class="events">
                        <?php foreach($events as $event): ?>
                        <div class="event">
                            <?php
                            if ($event->title == 'PT Session'){
                                $class = 'pt';
                                $action = 'session';
                            } else {
                                $class = 'diary';
                                $action = 'diary';
                            }
                            ?>
                            <a class="<?=$class;?>" href="/user/<?=$action;?>/id/<?=$event->id;?>">
                                <?=$event->title;?>
                            </a>
                        </div>
                        <?php endforeach; ?>
                    </span>
                <?php endif;?>
                </td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>