<?=$this->doctype() . PHP_EOL; ?>
<html>
    <head>
        <?php $this->dojo()->enable();
        if ($this->dojo()->isEnabled()){
            echo $this->dojo();
        }
        ?>
        <?php $this->headLink()->appendStylesheet('/css/global.css'); ?>
        <?=$this->headLink();?>
        <?=$this->headScript();?>
    </head>
    <body class="tundra">
        <div id="wrapper">
            <header>
            <?=$this->partial('partials/header.phtml'); ?>
            </header>
            <nav>
            <?= $this->navigation()->menu(); ?>
            </nav>
            <section id="content">
            <?=$this->layout()->content . PHP_EOL; ?>
            </section>
            <footer>
            <?=$this->partial('partials/footer.phtml'); ?>
            </footer>
        </div>
    </body>
</html>