<?php

/**
 * Model_Diary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Diary extends Model_Base_Diary
{

    /**
     *
     * @param int $diaryid 
     */
    public static function getDiary($diaryid) {
        $diary = Doctrine_Core::getTable('Model_Diary')->findOneById($diaryid);
        if ($diary){
            return $diary;
        } else {
            return false;
        }
    }

    /**
     *
     * @param Model_User $user
     * @return Doctrine_Collection | false
     */
    public static function getEvents(Model_User $user)
    {
        #$events = Doctrine_Core::getTable('Model_Diary')->findByUserid($user->id);
        $events = Doctrine_Query::create()->from('Model_Diary d')
                                         ->where('userid = ?', $user->id)
                                         ->andWhere('active = ?', true)
                                         ->execute();
        if ($events){
            return $events;
        } else {
            return false;
        }
    }

    public static function getDateRange(Model_User $user)
    {
        /**
         * @var Doctrine_Collection
         */
        $select = Doctrine_Query::create()->select('d.dateField')
                                          ->from('Model_Diary d')
                                          ->where('userid = ?', $user->id)
                                          ->andWhere('active = ?', true)
                                          ->orderBy('d.dateField ASC')
                                          ->execute();

        $first = new Zend_Date($select->getFirst()->dateField);
        $last = new Zend_Date($select->getLast()->dateField);

        return array('first' => $first, 'last' => $last);
    }

}