<?php

/**
 * Model_Diary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Diary extends Model_Base_Diary
{

    /**
     *
     * @param int $diaryid 
     */
    public static function getDiary($diaryid) {
        $diary = Doctrine_Core::getTable('Model_Diary')->findOneById($diaryid);
        if ($diary){
            return $diary;
        } else {
            return false;
        }
    }

    /**
     *
     * @param Model_User $user
     * @return Doctrine_Collection | false
     */
    public static function getEvents(Model_User $user)
    {
        $events = Doctrine_Core::getTable('Model_Diary')->findByUserid($user->id);
        if ($events){
            return $events;
        } else {
            return false;
        }
    }

}