<?php

/**
 * Model_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_User extends Model_Base_User
{

    const NOT_FOUND = 1;
    const WRONG_PW = 2;
    
    
    /**
     * authenticate method using Doctrine_Core
     * @param string $username
     * @param string $password
     * @throws Exception
     * @return Model_User 
     */
    public static function authenticate($username, $password) {
        $user = Doctrine_Core::getTable('Model_User')->findOneByUsername($username);
        if($user){
            $salt = new My_Auth_Salt();
            $salt->setDynamicSaltString($user->saltstring);
            $salt->setPassword($password);
            $seasonedpassword = $salt->getEncryptedPassword();
            
            if($user->password == $seasonedpassword){
                return $user;
            }
            
            throw new Exception(self::WRONG_PW);
        }

        throw new Exception(self::NOT_FOUND);

    }

    public static function findAll()
    {
        return Doctrine_Query::create()->from('Model_User u')->execute();
    }
}