<?php

/**
 * Model_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_User extends Model_Base_User
{

    const NOT_FOUND = 1;
    const WRONG_PW = 2;

    /**
     *
     * @var My_Acl_Role
     */
    protected $_role = My_Acl_Roles::GUEST;

    public static function findById($userid) {
        $user = Doctrine_Core::getTable('Model_User')->findOneById($userid);

        if($user)
            return $user;
        else
            return false;
    }
    
    
    /**
     * authenticate method using Doctrine_Core
     * @param string $username
     * @param string $password
     * @throws Exception
     * @return Model_User 
     */
    public static function authenticate($username, $password) {
        $user = Doctrine_Core::getTable('Model_User')->findOneByUsername($username);
        if($user){
            $salt = new My_Auth_Salt();
            $salt->setDynamicSaltString($user->saltstring);
            $salt->setPassword($password);
            $seasonedpassword = $salt->getEncryptedPassword();
            
            if($user->password == $seasonedpassword){
                
                return $user;
            }
            
            throw new Exception(self::WRONG_PW);
        }

        throw new Exception(self::NOT_FOUND);

    }

    public static function findAll()
    {
        $users = Doctrine_Core::getTable('Model_User')->findAll();
        $counter = 0;
        foreach($users as $user){
            if ($user->username == 'admin'){
                $users->remove($counter);
            }
            $counter++;
        }

        return $users;
    }

    public function setRole($role){
        $this->_role = $role;
    }

    public function getRole(){
        return $this->_role;
    }
}