<?php
$user = $this->user;

?>
<h1>User Control Panel</h1>
<ul id="cp-session-home">
    <li><h2>Upcoming Sessions</h2>
        <ul>
            <?= $this->partialLoop('partials/_sessionLoopUser.phtml', $this->upcoming); ?>
        </ul>
    </li>
    <li><h2>Previous Sessions</h2>
        <ul>
            <?= $this->partialLoop('partials/_sessionLoopUser.phtml', $this->previous); ?>
        </ul>
    </li>
</ul>

<?php
require_once(APPLICATION_PATH . '/../library/JpGraph/jpgraph.php');
require_once(APPLICATION_PATH . '/../library/JpGraph/jpgraph_bar.php');
require_once(APPLICATION_PATH . '/../library/JpGraph/jpgraph_line.php');
$jpgcache = '/tmp/jpgraph_cache/';
$graph_name = 'chart.png';
$graph = new Graph(700, 400, $graph_name, 0, 0);
$graph->img->SetMargin(30,30,30,30);
$graph->SetScale('textlin');
foreach($this->fitness as $fitness) {
    $bar = array();
    $bar[] = $fitness->beep;
    $bar[] = $fitness->toetaps;
    $bar[] = $fitness->pushups;
    $bar[] = $fitness->ninetyhang;
    $bar[] = $fitness->plank;
    $bar[] = $fitness->threeminstep;
    $bar[] = $fitness->twelveminrun;
    $bar[] = $fitness->waistcm;
    $bars[] = new BarPlot($bar);
}
$gbplot = new GroupBarPlot($bars);
$graph->add($gbplot);

foreach($this->fitness as $fitness){
    $fitnessArr = $fitness->getData();
    array_shift($fitnessArr);
    array_shift($fitnessArr);
    array_pop($fitnessArr);
    $columns = array();
    foreach($fitnessArr as $column => $data){
        $columns[] = $column;
    }
}
$graph->xaxis->SetTickLabels($columns);
$graph->Stroke();

print "<img src='{$jpgcache}{$graph_name}'>\n";
?>