<?php
$user = $this->user;

?>
<h1>User Control Panel</h1>
<ul id="cp-session-home">
    <li><h2>Upcoming Sessions</h2>
        <ul>
            <?= $this->partialLoop('partials/_sessionLoopUser.phtml', $this->upcoming); ?>
        </ul>
    </li>
    <li><h2>Previous Sessions</h2>
        <ul>
            <?= $this->partialLoop('partials/_sessionLoopUser.phtml', $this->previous); ?>
        </ul>
    </li>
</ul>