<?php $user = $this->user; ?>
<?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'); ?>
<?php $this->headScript()->captureStart(); ?>
function post(element) {
    var data = {};
    data['id'] = $(element).attr('name');
    $.post('/admin/generate-diary', data, function(data, textStatus) { alert('diary generated!') }, 'html');
}
<?php $this->headScript()->captureEnd(); ?>
<h1>Admin Control Panel</h1>
<ul>
    <li>
        <?=$user->name;?>
        <ul>
            <?php foreach($this->sessions as $session): ?>
            <?php
            $zendDate = new Zend_Date($session->datetime);
            $date = $zendDate->get(Zend_Date::DATE_FULL);
            $time = $zendDate->get(Zend_Date::TIME_SHORT);
            ?>
            <li>
                <a href="/admin/session?id=<?=$session->id?>">
                    <?=$session->sessiontype;?> for <?=$session->length;?> on <?=$date;?> at <?=$time;?> with <?=$session->User->name?>
                </a>
            <?php if ($session->invoiceid === null): ?>
                <a href="/admin/generate-invoice?id=<?=$session->id?>">Generate Invoice</a>
            <?php else: ?>
                <a href="/admin/view-invoice?id=<?=$session->id?>">View Invoice</a>
            <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </li>
</ul>
<?php if($this->message): ?>
<h2><?= $this->message; ?></h2>
<?php endif; ?>
<ul>
<?php foreach($this->users as $client): ?>
    <li><?=$client->name;?><input type="button" name="<?=$client->id?>" id="generate-<?=$client->id?>" value="Generate Food &amp; Exercise Diary" onclick="post(this);" /></li>
<?php endforeach;?>
</ul>
<a href="/admin/change-password">Change Password</a>
<a href="/login/logout">Logout</a>